<script setup>
import {onMounted , ref} from "vue";

let peerConnection = null ;
let localStream = null ;
let remoteStream = null;

let servers = {
  iceServers:[
    {
      urls:['stun:stun1.1.google.com:19302', 'stun:stun2.1.google.com:19302']
    }
  ]
}

onMounted( () => {
  init()
})

async function init(){
 localStream = await navigator.mediaDevices.getUserMedia({video:true , audio:true})
  document.getElementById('user-1').srcObject = localStream
}

let createPeerConnection = async (sdpType) => {
  peerConnection = new RTCPeerConnection(servers)

  remoteStream = new MediaStream()
  document.getElementById('user-2').srcObject = remoteStream

  localStream.getTracks().forEach( (track) =>
  { peerConnection.addTrack(track , localStream) })

  peerConnection.ontrack = async (event) => {
    event.streams[0].getTracks().forEach((track) => {remoteStream.addTrack(track)})
  }

  peerConnection.onicecandidate = async (event)=> {
    if(event.candidate){
      document.getElementById(sdpType).value = JSON.stringify(peerConnection.localDescription)

    }
  }
}
let createOffer = async () => {

  createPeerConnection('offer-sdp')
  let offer = await peerConnection.createOffer()
  await peerConnection.setLocalDescription(offer)
  document.getElementById('offer-sdp').value = JSON.stringify(offer)
}

let createAnswer = async () => {
  createPeerConnection('answer-sdp')

  let offer = document.getElementById('offer-sdp').value
  if(!offer)return alert('Retrieve Offer first')

  offer = JSON.parse(offer)
  await peerConnection.setRemoteDescription(offer)

  let answer = await  peerConnection.createAnswer()
  await peerConnection.setLocalDescription(answer)
  document.getElementById('answer-sdp').value = JSON.stringify(answer)
}

let addAnswer = async () => {
  let answer = document.getElementById('answer-sdp').value
  if(!answer)return alert('Retrieve Answer first')
  answer = JSON.parse(answer)

  if(!peerConnection.currentRemoteDescription){
    peerConnection.setRemoteDescription(answer)
  }

}
</script>

<template>

  <h1 class="d-flex justify-content-center text-danger">C4ISTAR webRTC</h1>
  <hr style="height:4px;border-width:0;color:black;background-color:gray">

  <div class="d-flex justify-content-center p-1">
    <video  id="user-1" class=" video-player w-50" style="border:3px solid black" autoplay playsinline></video>
    <video  id="user-2" class="video-player w-50" style="border:3px solid black" autoplay playsinline></video>
  </div>
  <hr style="height:4px;border-width:0;color:black;background-color:gray">

 <div class="d-flex justify-content-center">
   <div class="bg-success w-50 p-2 mb-4 rounded">
     <p><span class="fw-bold">Step 1:</span> User 1, click "Create offer" to generate SDP offer and copy offer from text area below.</p>
     <button class="btn btn-primary" @click="createOffer()">Create Offer</button>
   </div>
 </div>

  <div class="d-flex justify-content-center">
      <div class="w-50">
        <h5>SDP Offer:</h5>
       <textarea id="offer-sdp" cols="100" rows="3"></textarea>
      </div>
  </div>


  <div class="d-flex justify-content-center  mt-5">
    <div class="bg-success w-50 p-2 mb-4 rounded">
      <p><span class="fw-bold">Step 2:</span> User 2, paste SDP offer generated by user 1 into text area above, then click "Create Answer" to generate SDP answer and copy the answer from the text area below.</p>
      <button class="btn btn-primary" @click="createAnswer()">Create Answer</button>
    </div>
  </div>

  <div class="d-flex justify-content-center">
    <div class="w-50">
      <h5>SDP Answer:</h5>
      <textarea  id="answer-sdp" cols="100" rows="3"></textarea>
    </div>
  </div>

  <div class="d-flex justify-content-center  mt-5">
    <div class="bg-danger w-50 p-2 mb-4 rounded">
      <p><span class="fw-bold">Step 3:</span> User 1, paste SDP offer generated by user 2 into text area above and then click "Add Answer"

      </p>
      <button class="btn btn-primary" @click="addAnswer()">Add Answer</button>
    </div>
  </div>

</template>